/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Control.Cursors;
import Model.Artist;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Gabriel
 */
public class ArtistMenu extends javax.swing.JPanel {

    MainFrame mainFrame;
    ArrayList<Artist> directors;
    ArrayList<Artist> actors;
    ArrayList<Artist> writters;
    
    public ArtistMenu(MainFrame frame) {
        initComponents();
        this.mainFrame = frame;
        this.initializeArtists();
        
        if (mainFrame.userAccount != null) {
            signInButton.setText("Mi Cuenta");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        MainMenuLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        directorPic1 = new javax.swing.JLabel();
        directorName1 = new javax.swing.JLabel();
        directorBtn1 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        actorPic1 = new javax.swing.JLabel();
        actorBtn1 = new javax.swing.JButton();
        actorName1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        directorPic2 = new javax.swing.JLabel();
        directorBtn2 = new javax.swing.JButton();
        directorName2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        actorPic2 = new javax.swing.JLabel();
        actorBtn2 = new javax.swing.JButton();
        actorName2 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        writterPic2 = new javax.swing.JLabel();
        writterBtn2 = new javax.swing.JButton();
        writterName2 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        writterPic1 = new javax.swing.JLabel();
        writterBtn1 = new javax.swing.JButton();
        writterName1 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        MainMenu.setBackground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl.setText("Belphegor");

        jTextField1.setText("Buscar");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        signInButton.setBackground(new java.awt.Color(51, 51, 51));
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signInButton)
                .addGap(12, 12, 12))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MainMenuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInButton))
                .addContainerGap())
        );

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Director");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Actor");

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));

        directorName1.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        directorName1.setForeground(new java.awt.Color(255, 255, 255));
        directorName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        directorName1.setText("Not Found");

        directorBtn1.setBackground(new java.awt.Color(102, 102, 102));
        directorBtn1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        directorBtn1.setForeground(new java.awt.Color(255, 255, 255));
        directorBtn1.setText("Ver");
        directorBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(directorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(directorPic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directorName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directorPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directorName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton38.setBackground(new java.awt.Color(0, 0, 0));
        jButton38.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("Ver todos");
        jButton38.setBorder(null);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));

        actorBtn1.setBackground(new java.awt.Color(102, 102, 102));
        actorBtn1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        actorBtn1.setForeground(new java.awt.Color(255, 255, 255));
        actorBtn1.setText("Ver");
        actorBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actorBtn1ActionPerformed(evt);
            }
        });

        actorName1.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        actorName1.setForeground(new java.awt.Color(255, 255, 255));
        actorName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actorName1.setText("Not Found");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(actorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actorPic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actorName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actorPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actorName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actorBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(51, 51, 51));

        directorBtn2.setBackground(new java.awt.Color(102, 102, 102));
        directorBtn2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        directorBtn2.setForeground(new java.awt.Color(255, 255, 255));
        directorBtn2.setText("Ver");
        directorBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorBtn2ActionPerformed(evt);
            }
        });

        directorName2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        directorName2.setForeground(new java.awt.Color(255, 255, 255));
        directorName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        directorName2.setText("Not Found");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(directorBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directorName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(directorPic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directorPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directorName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directorBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));

        actorBtn2.setBackground(new java.awt.Color(102, 102, 102));
        actorBtn2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        actorBtn2.setForeground(new java.awt.Color(255, 255, 255));
        actorBtn2.setText("Ver");
        actorBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actorBtn2ActionPerformed(evt);
            }
        });

        actorName2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        actorName2.setForeground(new java.awt.Color(255, 255, 255));
        actorName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actorName2.setText("Not Found");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(actorBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actorPic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actorName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actorPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actorName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actorBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(51, 51, 51));

        writterBtn2.setBackground(new java.awt.Color(102, 102, 102));
        writterBtn2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        writterBtn2.setForeground(new java.awt.Color(255, 255, 255));
        writterBtn2.setText("Ver");
        writterBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writterBtn2ActionPerformed(evt);
            }
        });

        writterName2.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        writterName2.setForeground(new java.awt.Color(255, 255, 255));
        writterName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        writterName2.setText("Not Found");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(writterBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(writterPic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(writterName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(writterPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writterName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writterBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(51, 51, 51));

        writterBtn1.setBackground(new java.awt.Color(102, 102, 102));
        writterBtn1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        writterBtn1.setForeground(new java.awt.Color(255, 255, 255));
        writterBtn1.setText("Ver");
        writterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writterBtn1ActionPerformed(evt);
            }
        });

        writterName1.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        writterName1.setForeground(new java.awt.Color(255, 255, 255));
        writterName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        writterName1.setText("Not Found");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(writterBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(writterPic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(writterName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(writterPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writterName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writterBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Writter");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Productos");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                        .addComponent(jButton38)
                        .addGap(55, 55, 55))))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addGap(18, 18, 18)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MainMenuLayout.createSequentialGroup()
                                        .addComponent(jLabel51)
                                        .addGap(368, 368, 368))
                                    .addGroup(MainMenuLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        if (mainFrame.userAccount == null) {
            mainFrame.showPage("SignInPage", new SignInPage(mainFrame, this));
        }
        else {
            mainFrame.showPage("ManageAccount", new ManageAccount(mainFrame, this));
        }
    }//GEN-LAST:event_signInButtonActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        mainFrame.showPage("viewAllArtists", new ViewAllArtists(mainFrame, this));
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame.showPage("MainMenu", new MainMenu(mainFrame));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void directorBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorBtn1ActionPerformed
        try {
            mainFrame.showPage("ViewArtist", new ViewArtist(mainFrame, this,
                               this.directors.get(0).getId()));
        } catch (Exception e) {
            mainFrame.showError("No se ha encontrado al artista");
        }
    }//GEN-LAST:event_directorBtn1ActionPerformed

    private void actorBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actorBtn1ActionPerformed
        try {
            mainFrame.showPage("ViewArtist", new ViewArtist(mainFrame, this,
                               this.actors.get(0).getId()));
        } catch (Exception e) {
            mainFrame.showError("No se ha encontrado al artista");
        }
    }//GEN-LAST:event_actorBtn1ActionPerformed

    private void directorBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorBtn2ActionPerformed
        try {
            mainFrame.showPage("ViewArtist", new ViewArtist(mainFrame, this,
                               this.directors.get(1).getId()));
        } catch (Exception e) {
            mainFrame.showError("No se ha encontrado al artista");
        }
    }//GEN-LAST:event_directorBtn2ActionPerformed

    private void actorBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actorBtn2ActionPerformed
        try {
            mainFrame.showPage("ViewArtist", new ViewArtist(mainFrame, this,
                               this.actors.get(1).getId()));
        } catch (Exception e) {
            mainFrame.showError("No se ha encontrado al artista");
        }
    }//GEN-LAST:event_actorBtn2ActionPerformed

    private void writterBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writterBtn2ActionPerformed
        try {
            mainFrame.showPage("ViewArtist", new ViewArtist(mainFrame, this,
                               this.writters.get(1).getId()));
        } catch (Exception e) {
            mainFrame.showError("No se ha encontrado al artista");
        }
    }//GEN-LAST:event_writterBtn2ActionPerformed

    private void writterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writterBtn1ActionPerformed
        try {
            mainFrame.showPage("ViewArtist", new ViewArtist(mainFrame, this,
                               this.writters.get(0).getId()));
        } catch (Exception e) {
            mainFrame.showError("No se ha encontrado al artista");
        }
    }//GEN-LAST:event_writterBtn1ActionPerformed
    
    private void initializeArtists() {
        this.initializeDirectors();
        this.initializeActors();
        this.initializeWritters();
    }
    
    private void initializeDirectors() {
        try {
            this.directors = Cursors.getArtistsOfType(2);
            
            Artist director1 = this.directors.get(0);
            this.directorName1.setText(director1.getName());
            this.setLabelIcon(this.directorPic1, Cursors.getArtistPhotos(director1.getId()).get(0));
        } catch (Exception e) {
            System.out.println("No hay directores");
        }
        
        try {
            Artist director2 = this.directors.get(1);
            this.directorName2.setText(director2.getName());
            this.setLabelIcon(this.directorPic2, Cursors.getArtistPhotos(director2.getId()).get(0));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void initializeActors() {
        try {
            this.actors = Cursors.getArtistsOfType(1);
            
            Artist actor1 = this.actors.get(0);
            this.actorName1.setText(actor1.getName());
            this.setLabelIcon(this.actorPic1, Cursors.getArtistPhotos(actor1.getId()).get(0));
        } catch (Exception e) {
            System.out.println("No hay actores");
        }
        
        try {
            Artist actor2 = this.actors.get(1);
            this.actorName2.setText(actor2.getName());
            this.setLabelIcon(this.actorPic2, Cursors.getArtistPhotos(actor2.getId()).get(0));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void initializeWritters() {
        try {
            this.writters = Cursors.getArtistsOfType(3);
            
            Artist writter1 = directors.get(0);
            this.directorName1.setText(writter1.getName());
            this.setLabelIcon(this.writterPic1, Cursors.getArtistPhotos(writter1.getId()).get(0));
        } catch (Exception e) {
            System.out.println("No hay escritores");
        }
        
        try {
            Artist writter2 = directors.get(1);
            this.directorName2.setText(writter2.getName());
            this.setLabelIcon(this.writterPic2, Cursors.getArtistPhotos(writter2.getId()).get(0));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void setLabelIcon(JLabel label, String path) {
    //Receives a label and an image path, sets the label's icon to the image.
        
        if(path != null) {
            File file = new File(path);
            BufferedImage originalImage = null;
            try {
                originalImage = ImageIO.read(file);
            }
            catch (Exception e) {
                mainFrame.showError("Error al cargar imagen");
            }
            
            Image scaledImage = originalImage.getScaledInstance(86, 111, Image.SCALE_SMOOTH);
            // Create a new ImageIcon
            ImageIcon icon = new ImageIcon(scaledImage);
            label.setIcon(icon);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JLabel MainMenuLbl;
    private javax.swing.JButton actorBtn1;
    private javax.swing.JButton actorBtn2;
    private javax.swing.JLabel actorName1;
    private javax.swing.JLabel actorName2;
    private javax.swing.JLabel actorPic1;
    private javax.swing.JLabel actorPic2;
    private javax.swing.JButton directorBtn1;
    private javax.swing.JButton directorBtn2;
    private javax.swing.JLabel directorName1;
    private javax.swing.JLabel directorName2;
    private javax.swing.JLabel directorPic1;
    private javax.swing.JLabel directorPic2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton38;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton writterBtn1;
    private javax.swing.JButton writterBtn2;
    private javax.swing.JLabel writterName1;
    private javax.swing.JLabel writterName2;
    private javax.swing.JLabel writterPic1;
    private javax.swing.JLabel writterPic2;
    // End of variables declaration//GEN-END:variables
}
