package View;
import Model.*;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import Control.*;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.ListModel;

public class ManageAccount extends javax.swing.JPanel {
    MainFrame mainFrame;
    JPanel prev;
        
    public ManageAccount(MainFrame mainFrame, JPanel prev) {
        this.mainFrame = mainFrame;
        this.prev = prev;
        initComponents();
        helloTxt.setText("Hola, " + mainFrame.userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        AppBar = new javax.swing.JPanel();
        MainMenuLbl2 = new javax.swing.JLabel();
        helloTxt = new javax.swing.JLabel();
        favs_button = new javax.swing.JButton();
        owned_button = new javax.swing.JButton();
        viewed_button = new javax.swing.JButton();
        cart_button = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Favorites = new javax.swing.JPanel();
        AppBar1 = new javax.swing.JPanel();
        MainMenuLbl3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        favoritesList = new javax.swing.JList<>();
        ViewProductBtn = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        Menu.setBackground(new java.awt.Color(0, 0, 0));

        AppBar.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl2.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl2.setText("Belphegor");

        javax.swing.GroupLayout AppBarLayout = new javax.swing.GroupLayout(AppBar);
        AppBar.setLayout(AppBarLayout);
        AppBarLayout.setHorizontalGroup(
            AppBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBarLayout.setVerticalGroup(
            AppBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        helloTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helloTxt.setForeground(new java.awt.Color(255, 255, 255));
        helloTxt.setText("Hola, Usuario02");

        favs_button.setBackground(new java.awt.Color(51, 51, 51));
        favs_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        favs_button.setForeground(new java.awt.Color(255, 255, 255));
        favs_button.setText("Favoritos");
        favs_button.setBorderPainted(false);
        favs_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favs_buttonActionPerformed(evt);
            }
        });

        owned_button.setBackground(new java.awt.Color(51, 51, 51));
        owned_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        owned_button.setForeground(new java.awt.Color(255, 255, 255));
        owned_button.setText("Compras");
        owned_button.setBorderPainted(false);
        owned_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owned_buttonActionPerformed(evt);
            }
        });

        viewed_button.setBackground(new java.awt.Color(51, 51, 51));
        viewed_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewed_button.setForeground(new java.awt.Color(255, 255, 255));
        viewed_button.setText("Vistos");
        viewed_button.setBorderPainted(false);
        viewed_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewed_buttonActionPerformed(evt);
            }
        });

        cart_button.setBackground(new java.awt.Color(51, 51, 51));
        cart_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cart_button.setForeground(new java.awt.Color(255, 255, 255));
        cart_button.setText("Carrito");
        cart_button.setBorderPainted(false);
        cart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cart_buttonActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Atrás");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Admin");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(favs_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cart_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewed_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owned_button))
                    .addComponent(helloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(AppBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favs_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewed_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cart_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(owned_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(Menu, "Menu");

        Favorites.setBackground(new java.awt.Color(0, 0, 0));

        AppBar1.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl3.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl3.setText("Belphegor");

        javax.swing.GroupLayout AppBar1Layout = new javax.swing.GroupLayout(AppBar1);
        AppBar1.setLayout(AppBar1Layout);
        AppBar1Layout.setHorizontalGroup(
            AppBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBar1Layout.setVerticalGroup(
            AppBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Favoritos:");

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Atrás");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        favoritesList.setBackground(new java.awt.Color(51, 51, 51));
        favoritesList.setForeground(new java.awt.Color(255, 255, 255));
        favoritesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Aun no tienes favoritos." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(favoritesList);

        ViewProductBtn.setText("Ver");
        ViewProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FavoritesLayout = new javax.swing.GroupLayout(Favorites);
        Favorites.setLayout(FavoritesLayout);
        FavoritesLayout.setHorizontalGroup(
            FavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FavoritesLayout.createSequentialGroup()
                .addGroup(FavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(ViewProductBtn)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        FavoritesLayout.setVerticalGroup(
            FavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavoritesLayout.createSequentialGroup()
                .addComponent(AppBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewProductBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        add(Favorites, "Favorites");
    }// </editor-fold>//GEN-END:initComponents

    private void favs_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favs_buttonActionPerformed
        try {
            int idWishlist = Cursors.getWishlistId(mainFrame.userAccount.getId_user());
            DefaultListModel model = mainFrame.buildListModel(Cursors.getProductsInWishlist(idWishlist));
            favoritesList.setModel(model);
        }
        catch (Exception e) {
            mainFrame.showError("Error al obtener favoritos.");
            return;
        }
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Favorites");
    }//GEN-LAST:event_favs_buttonActionPerformed

    private void owned_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owned_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owned_buttonActionPerformed

    private void viewed_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewed_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewed_buttonActionPerformed

    private void cart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cart_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cart_buttonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainFrame.showPage("MainMenu", prev);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Menu");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ViewProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductBtnActionPerformed
        int index = favoritesList.getSelectedIndex();
        if (index < 0) {
            mainFrame.showError("Debe seleccionar un elemento.");
            return;
        }
        ListModel model = favoritesList.getModel();
        Product product = (Product) model.getElementAt(index);
        mainFrame.showPage("ViewMovie", new ViewMovie(mainFrame, this, product));
    }//GEN-LAST:event_ViewProductBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (mainFrame.userAccount != null && mainFrame.userAccount.getId_accountType() != 1) {
            mainFrame.showError("No tiene permisos de administrador");
            return;
        }
        System.out.println(mainFrame.userAccount.getId_accountType());
        mainFrame.showPage("AdminPage", new AdminPage(mainFrame, this));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppBar;
    private javax.swing.JPanel AppBar1;
    private javax.swing.JPanel Favorites;
    private javax.swing.JLabel MainMenuLbl2;
    private javax.swing.JLabel MainMenuLbl3;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton ViewProductBtn;
    private javax.swing.JButton cart_button;
    private javax.swing.JList<String> favoritesList;
    private javax.swing.JButton favs_button;
    private javax.swing.JLabel helloTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton owned_button;
    private javax.swing.JButton viewed_button;
    // End of variables declaration//GEN-END:variables
}
