package View;
import Model.*;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import Control.*;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ManageAccount extends javax.swing.JPanel {
    MainFrame mainFrame;
    JPanel prev;
    ArrayList<Product> ownedProducts;
        
    public ManageAccount(MainFrame mainFrame, JPanel prev) {
        this.mainFrame = mainFrame;
        this.prev = prev;
        initComponents();
        helloTxt.setText("Hola, " + mainFrame.userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        AppBar = new javax.swing.JPanel();
        MainMenuLbl2 = new javax.swing.JLabel();
        helloTxt = new javax.swing.JLabel();
        favs_button = new javax.swing.JButton();
        owned_button = new javax.swing.JButton();
        viewed_button = new javax.swing.JButton();
        cart_button = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Favorites = new javax.swing.JPanel();
        AppBar1 = new javax.swing.JPanel();
        MainMenuLbl3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        favoritesList = new javax.swing.JList<>();
        ViewProductBtn = new javax.swing.JButton();
        Cart = new javax.swing.JPanel();
        AppBar2 = new javax.swing.JPanel();
        MainMenuLbl4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        ViewProductBtn1 = new javax.swing.JButton();
        PayButton = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        PayTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vencimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pinTarjeta = new javax.swing.JTextField();
        Viewed = new javax.swing.JPanel();
        AppBar3 = new javax.swing.JPanel();
        MainMenuLbl5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewedList = new javax.swing.JList<>();
        ViewProductBtn2 = new javax.swing.JButton();
        Owned = new javax.swing.JPanel();
        AppBar4 = new javax.swing.JPanel();
        MainMenuLbl6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ownedList = new javax.swing.JList<>();
        ViewProductBtn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ownedFilterCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        Menu.setBackground(new java.awt.Color(0, 0, 0));

        AppBar.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl2.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl2.setText("Belphegor");

        javax.swing.GroupLayout AppBarLayout = new javax.swing.GroupLayout(AppBar);
        AppBar.setLayout(AppBarLayout);
        AppBarLayout.setHorizontalGroup(
            AppBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBarLayout.setVerticalGroup(
            AppBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        helloTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helloTxt.setForeground(new java.awt.Color(255, 255, 255));
        helloTxt.setText("Hola, Usuario02");

        favs_button.setBackground(new java.awt.Color(51, 51, 51));
        favs_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        favs_button.setForeground(new java.awt.Color(255, 255, 255));
        favs_button.setText("Favoritos");
        favs_button.setBorderPainted(false);
        favs_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favs_buttonActionPerformed(evt);
            }
        });

        owned_button.setBackground(new java.awt.Color(51, 51, 51));
        owned_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        owned_button.setForeground(new java.awt.Color(255, 255, 255));
        owned_button.setText("Compras");
        owned_button.setBorderPainted(false);
        owned_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owned_buttonActionPerformed(evt);
            }
        });

        viewed_button.setBackground(new java.awt.Color(51, 51, 51));
        viewed_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewed_button.setForeground(new java.awt.Color(255, 255, 255));
        viewed_button.setText("Vistos");
        viewed_button.setBorderPainted(false);
        viewed_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewed_buttonActionPerformed(evt);
            }
        });

        cart_button.setBackground(new java.awt.Color(51, 51, 51));
        cart_button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cart_button.setForeground(new java.awt.Color(255, 255, 255));
        cart_button.setText("Carrito");
        cart_button.setBorderPainted(false);
        cart_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cart_buttonActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Atrás");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Admin");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(favs_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cart_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewed_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(owned_button))
                    .addComponent(helloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(AppBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favs_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewed_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cart_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(owned_button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(Menu, "Menu");

        Favorites.setBackground(new java.awt.Color(0, 0, 0));

        AppBar1.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl3.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl3.setText("Belphegor");

        javax.swing.GroupLayout AppBar1Layout = new javax.swing.GroupLayout(AppBar1);
        AppBar1.setLayout(AppBar1Layout);
        AppBar1Layout.setHorizontalGroup(
            AppBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBar1Layout.setVerticalGroup(
            AppBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Favoritos:");

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Atrás");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        favoritesList.setBackground(new java.awt.Color(51, 51, 51));
        favoritesList.setForeground(new java.awt.Color(255, 255, 255));
        favoritesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Aun no tienes favoritos." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(favoritesList);

        ViewProductBtn.setText("Ver");
        ViewProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FavoritesLayout = new javax.swing.GroupLayout(Favorites);
        Favorites.setLayout(FavoritesLayout);
        FavoritesLayout.setHorizontalGroup(
            FavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FavoritesLayout.createSequentialGroup()
                .addGroup(FavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(ViewProductBtn))
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FavoritesLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FavoritesLayout.setVerticalGroup(
            FavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavoritesLayout.createSequentialGroup()
                .addComponent(AppBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewProductBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        add(Favorites, "Favorites");

        Cart.setBackground(new java.awt.Color(0, 0, 0));

        AppBar2.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl4.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl4.setText("Belphegor");

        javax.swing.GroupLayout AppBar2Layout = new javax.swing.GroupLayout(AppBar2);
        AppBar2.setLayout(AppBar2Layout);
        AppBar2Layout.setHorizontalGroup(
            AppBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBar2Layout.setVerticalGroup(
            AppBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Carrito:");

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Atrás");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        ViewProductBtn1.setText("Ver");
        ViewProductBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductBtn1ActionPerformed(evt);
            }
        });

        PayButton.setBackground(new java.awt.Color(51, 51, 51));
        PayButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PayButton.setForeground(new java.awt.Color(255, 255, 255));
        PayButton.setText("Pagar");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("Total: $44.87");

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(cartTable);

        PayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vencimiento:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Número tarjeta");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pin");

        pinTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CartLayout = new javax.swing.GroupLayout(Cart);
        Cart.setLayout(CartLayout);
        CartLayout.setHorizontalGroup(
            CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CartLayout.createSequentialGroup()
                .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CartLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CartLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(264, 264, 264))
                            .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CartLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(ViewProductBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CartLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(CartLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(PayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pinTarjeta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vencimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        CartLayout.setVerticalGroup(
            CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CartLayout.createSequentialGroup()
                .addComponent(AppBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CartLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CartLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ViewProductBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7))
                            .addGroup(CartLayout.createSequentialGroup()
                                .addComponent(total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 25, Short.MAX_VALUE))))
                    .addGroup(CartLayout.createSequentialGroup()
                        .addComponent(PayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pinTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(Cart, "Cart");

        Viewed.setBackground(new java.awt.Color(0, 0, 0));

        AppBar3.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl5.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl5.setText("Belphegor");

        javax.swing.GroupLayout AppBar3Layout = new javax.swing.GroupLayout(AppBar3);
        AppBar3.setLayout(AppBar3Layout);
        AppBar3Layout.setHorizontalGroup(
            AppBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBar3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBar3Layout.setVerticalGroup(
            AppBar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBar3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vistos:");

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Atrás");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        viewedList.setBackground(new java.awt.Color(51, 51, 51));
        viewedList.setForeground(new java.awt.Color(255, 255, 255));
        viewedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Aun no tienes favoritos." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(viewedList);

        ViewProductBtn2.setText("Ver");
        ViewProductBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewedLayout = new javax.swing.GroupLayout(Viewed);
        Viewed.setLayout(ViewedLayout);
        ViewedLayout.setHorizontalGroup(
            ViewedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewedLayout.createSequentialGroup()
                .addGroup(ViewedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8))
                    .addGroup(ViewedLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(ViewProductBtn2))
                    .addGroup(ViewedLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewedLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewedLayout.setVerticalGroup(
            ViewedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewedLayout.createSequentialGroup()
                .addComponent(AppBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewProductBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addContainerGap())
        );

        add(Viewed, "Viewed");

        Owned.setBackground(new java.awt.Color(0, 0, 0));

        AppBar4.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl6.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl6.setText("Belphegor");

        javax.swing.GroupLayout AppBar4Layout = new javax.swing.GroupLayout(AppBar4);
        AppBar4.setLayout(AppBar4Layout);
        AppBar4Layout.setHorizontalGroup(
            AppBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppBar4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AppBar4Layout.setVerticalGroup(
            AppBar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppBar4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Compras:");

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Atrás");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        ownedList.setBackground(new java.awt.Color(51, 51, 51));
        ownedList.setForeground(new java.awt.Color(255, 255, 255));
        ownedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Aun no tienes favoritos." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ownedList);

        ViewProductBtn3.setText("Ver");
        ViewProductBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductBtn3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtro:");

        ownedFilterCombo.setBackground(new java.awt.Color(51, 51, 51));
        ownedFilterCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ownedFilterCombo.setForeground(new java.awt.Color(255, 255, 255));
        ownedFilterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "3 meses", "6 meses", "1 año" }));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OwnedLayout = new javax.swing.GroupLayout(Owned);
        Owned.setLayout(OwnedLayout);
        OwnedLayout.setHorizontalGroup(
            OwnedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBar4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OwnedLayout.createSequentialGroup()
                .addGroup(OwnedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OwnedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9))
                    .addGroup(OwnedLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(ViewProductBtn3))
                    .addGroup(OwnedLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OwnedLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(OwnedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OwnedLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(OwnedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ownedFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(OwnedLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton1)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        OwnedLayout.setVerticalGroup(
            OwnedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnedLayout.createSequentialGroup()
                .addComponent(AppBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OwnedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OwnedLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownedFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewProductBtn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );

        add(Owned, "Owned");
    }// </editor-fold>//GEN-END:initComponents

    private void favs_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favs_buttonActionPerformed
        try {
            int idWishlist = Cursors.getWishlistId(mainFrame.userAccount.getId_user());
            DefaultListModel model = mainFrame.buildListModel(Cursors.getProductsInWishlist(idWishlist));
            favoritesList.setModel(model);
        }
        catch (Exception e) {
            mainFrame.showError("Error al obtener favoritos.");
            return;
        }
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Favorites");
    }//GEN-LAST:event_favs_buttonActionPerformed

    private void owned_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owned_buttonActionPerformed
        try {
            int idUser = mainFrame.userAccount.getId_user();
            ownedProducts = Cursors.getOwnedProducts(idUser);
            DefaultListModel model = new DefaultListModel();
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat outputFormat = new SimpleDateFormat("dd-MM-yyyy");
            for (Product p : ownedProducts) {
                String dateStr = p.getDateBought();
                Date date = inputFormat.parse(dateStr);
                dateStr = outputFormat.format(date);
                String element = p.getTitle() + " | " + dateStr;
                model.addElement(element);
            }
            ownedList.setModel(model);
        }
        catch (Exception e) {
            mainFrame.showError("Error al obtener compras.");
            System.out.println(e);
            return;
        }
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Owned");
    }//GEN-LAST:event_owned_buttonActionPerformed

    private void viewed_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewed_buttonActionPerformed
        try {
            int idUser = mainFrame.userAccount.getId_user();
            DefaultListModel model = mainFrame.buildListModel(Cursors.getViewedProducts(idUser));
            viewedList.setModel(model);
        }
        catch (Exception e) {
            mainFrame.showError("Error al obtener historial.");
            return;
        }
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Viewed");
    }//GEN-LAST:event_viewed_buttonActionPerformed

    private void cart_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cart_buttonActionPerformed
        DefaultTableModel cartModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String[] columns = {"Producto", "Precio"};
        cartModel.setColumnIdentifiers(columns);
        float totalPrice = 0;
        try {
            int idCart = Cursors.getCartId(mainFrame.userAccount.getId_user());
            ArrayList<Product> products = Cursors.getProductsInCart(idCart);
            for (Product p : products) {
                Object[] row = new Object[2];
                row[0] = p;
                row[1] = "$" + Float.toString(p.getPrice());
                cartModel.addRow(row);
                totalPrice += p.getPrice();
            }
        }
        catch (Exception e) {
            mainFrame.showError("Error al obtener carrito.");
            return;
        }
        total.setText("Total: $" + Float.toString(totalPrice));
        cartTable.setModel(cartModel);
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Cart");
    }//GEN-LAST:event_cart_buttonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainFrame.showPage("MainMenu", prev);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Menu");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ViewProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductBtnActionPerformed
        int index = favoritesList.getSelectedIndex();
        if (index < 0) {
            mainFrame.showError("Debe seleccionar un elemento.");
            return;
        }
        ListModel model = favoritesList.getModel();
        Product product = (Product) model.getElementAt(index);
        try{
            int isMovie = Cursors.isMovie(product.getId());
            if (isMovie == 1)
                mainFrame.showPage("ViewMovie", new ViewMovie(mainFrame, this, product));
            else
                mainFrame.showPage("ViewSeries", new ViewSeries(mainFrame, this, product));
        }
        catch (Exception e) {
            mainFrame.showError("Error al mostrar producto.");
        }
    }//GEN-LAST:event_ViewProductBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (mainFrame.userAccount != null && mainFrame.userAccount.getId_accountType() != 1) {
            mainFrame.showError("No tiene permisos de administrador");
            return;
        }
        mainFrame.showPage("AdminPage", new AdminPage(mainFrame, this));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Menu");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ViewProductBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductBtn1ActionPerformed
        int index = cartTable.getSelectedRow();
        if (index < 0) {
            mainFrame.showError("Debe seleccionar un elemento.");
            return;
        }
        TableModel model = cartTable.getModel();
        Product product = (Product) model.getValueAt(index, 0);
        try {
            int isMovie = Cursors.isMovie(product.getId());
            if (isMovie == 1)
                mainFrame.showPage("ViewMovie", new ViewMovie(mainFrame, this, product));
            else
                mainFrame.showPage("ViewSeries", new ViewSeries(mainFrame, this, product));
        }
        catch (Exception e) {}
    }//GEN-LAST:event_ViewProductBtn1ActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        try {
            int number = Integer.parseInt(PayTextField.getText());
            int pin = Integer.parseInt(pinTarjeta.getText());
            Date date = vencimiento.getDate();
        }
        catch(Exception e) {
            mainFrame.showError("Ingrese una tarjeta válida.");
            return;
        }
        
        try {
            
            int idUser = mainFrame.userAccount.getId_user();
            LocalDate currentDate = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String purchaseDate = formatter.format(currentDate);
            
            TableModel model = cartTable.getModel();
            
            for (int i = 0; i < cartTable.getModel().getRowCount(); i++) {
                Product product = (Product) model.getValueAt(i, 0);
                int idProduct = product.getId();
                Insertions.InsertOwnedProduct(idProduct, idUser, purchaseDate);
                int idCart = Cursors.getCartId(idUser);
                Deletions.deleteFromCart(idCart, idProduct);
            }
            DefaultTableModel tableModel = new DefaultTableModel();
            cartTable.setModel(tableModel);
        }
        catch(Exception e) {
            mainFrame.showError("Error al escribir en la base de datos.");
            System.out.println(e.getMessage());
            return;
        }
        mainFrame.showPage("Prev", prev);
    }//GEN-LAST:event_PayButtonActionPerformed

    private void PayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayTextFieldActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Menu");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ViewProductBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductBtn2ActionPerformed
        int index = viewedList.getSelectedIndex();
        if (index < 0) {
            mainFrame.showError("Debe seleccionar un elemento.");
            return;
        }
        ListModel model = viewedList.getModel();
        Product product = (Product) model.getElementAt(index);
        try{
            int isMovie = Cursors.isMovie(product.getId());
            if (isMovie == 1)
                mainFrame.showPage("ViewMovie", new ViewMovie(mainFrame, this, product));
            else
                mainFrame.showPage("ViewSeries", new ViewSeries(mainFrame, this, product));
        }
        catch (Exception e) {
            mainFrame.showError("Error al mostrar producto.");
        }
    }//GEN-LAST:event_ViewProductBtn2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "Menu");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ViewProductBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductBtn3ActionPerformed
        int index = ownedList.getSelectedIndex();
        if (index < 0) {
            mainFrame.showError("Debe seleccionar un elemento.");
            return;
        }
        Product product = ownedProducts.get(index);
        try{
            int isMovie = Cursors.isMovie(product.getId());
            if (isMovie == 1)
                mainFrame.showPage("ViewMovie", new ViewMovie(mainFrame, this, product));
            else
                mainFrame.showPage("ViewSeries", new ViewSeries(mainFrame, this, product));
        }
        catch (Exception e) {
            mainFrame.showError("Error al mostrar producto.");
        }
    }//GEN-LAST:event_ViewProductBtn3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int idUser = mainFrame.userAccount.getId_user();
            ownedProducts = switch (ownedFilterCombo.getSelectedIndex()) {
                case 0 -> Cursors.getOwnedProducts(idUser);
                case 1 -> Cursors.getOwnedProductsFilter(idUser, -3);
                case 2 -> Cursors.getOwnedProductsFilter(idUser, -6);
                case 3 -> Cursors.getOwnedProductsFilter(idUser, -12);
                default -> Cursors.getOwnedProducts(idUser);
            };
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat outputFormat = new SimpleDateFormat("dd-MM-yyyy");
            DefaultListModel model = new DefaultListModel();
            for (Product p : ownedProducts) {
                String dateStr = p.getDateBought();
                Date date = inputFormat.parse(dateStr);
                dateStr = outputFormat.format(date);
                String element = p.getTitle() + " | " + dateStr;
                model.addElement(element);
            }
            ownedList.setModel(model);
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pinTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppBar;
    private javax.swing.JPanel AppBar1;
    private javax.swing.JPanel AppBar2;
    private javax.swing.JPanel AppBar3;
    private javax.swing.JPanel AppBar4;
    private javax.swing.JPanel Cart;
    private javax.swing.JPanel Favorites;
    private javax.swing.JLabel MainMenuLbl2;
    private javax.swing.JLabel MainMenuLbl3;
    private javax.swing.JLabel MainMenuLbl4;
    private javax.swing.JLabel MainMenuLbl5;
    private javax.swing.JLabel MainMenuLbl6;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Owned;
    private javax.swing.JButton PayButton;
    private javax.swing.JTextField PayTextField;
    private javax.swing.JButton ViewProductBtn;
    private javax.swing.JButton ViewProductBtn1;
    private javax.swing.JButton ViewProductBtn2;
    private javax.swing.JButton ViewProductBtn3;
    private javax.swing.JPanel Viewed;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton cart_button;
    private javax.swing.JList<String> favoritesList;
    private javax.swing.JButton favs_button;
    private javax.swing.JLabel helloTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> ownedFilterCombo;
    private javax.swing.JList<String> ownedList;
    private javax.swing.JButton owned_button;
    private javax.swing.JTextField pinTarjeta;
    private javax.swing.JLabel total;
    private com.toedter.calendar.JDateChooser vencimiento;
    private javax.swing.JList<String> viewedList;
    private javax.swing.JButton viewed_button;
    // End of variables declaration//GEN-END:variables
}
