package View;

import Control.*;
import Model.*;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ViewReviewsProduct extends javax.swing.JPanel {
    Product product;
    MainFrame mainFrame;
    JPanel prev;
    boolean rated;
    int userReviewId;
    
    public ViewReviewsProduct(MainFrame mainFrame, Product product, JPanel prev) {
        this.product = product;
        this.mainFrame = mainFrame;
        this.prev = prev;
        rated = false;
        initComponents();
        loadData();
    }
    
    public void loadData() {
        ArrayList<Review> reviews;
        movieNameTxt.setText(product.getTitle());
        try {
            reviews = Cursors.getProductReviews(product.getId());
        }
        catch (Exception e) {
            mainFrame.showError("Error al cargar reviews.");
            return;
        }
        DefaultTableModel reviewModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String[] columns = {"Usuario", "Puntuación"};
        reviewModel.setColumnIdentifiers(columns);
        
        try {
            for (Review r : reviews) {
                Object[] row = new Object[2];
                row[0] = Cursors.getUsernameByUserId(r.getId_user());
                row[1] = r;
                reviewModel.addRow(row);
                
                if (mainFrame.userAccount != null && r.getId_user() == mainFrame.userAccount.getId_user()) {
                    addButton.setText("Actualizar");
                    newReviewTxt.setText(r.getDescription());
                    newReviewRating.setSelectedIndex(5 - r.getScore());
                    rated = true;
                    userReviewId = r.getId();
                }
            }
        }
        catch (Exception e) {
            mainFrame.showError("Error al cargar las reviews");
        }
        reviewTable.setModel(reviewModel);
        
        if (!rated) {
            removeButton.setEnabled(false);
        }
        ListSelectionModel selectionModel = reviewTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            if (reviewTable.getSelectedRow() == -1) {
                reviewTable.setRowSelectionInterval(0, 0);
            }
            if (!e.getValueIsAdjusting()) {
                TableModel model = reviewTable.getModel();
                int index = reviewTable.getSelectedRow();
                Review review = (Review) model.getValueAt(index, 1);
                selectedReviewTxt.setText(review.getDescription());
            }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewReviewsProduct = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        MainMenuLbl2 = new javax.swing.JLabel();
        movieNameTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedReviewTxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        newReviewTxt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        newReviewRating = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        ViewReviewsProduct.setBackground(new java.awt.Color(0, 0, 0));

        jPanel19.setBackground(new java.awt.Color(51, 51, 51));

        MainMenuLbl2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MainMenuLbl2.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLbl2.setText("Belphegor");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainMenuLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        movieNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        movieNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        movieNameTxt.setText("Nombre Película");

        reviewTable.setBackground(new java.awt.Color(51, 51, 51));
        reviewTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reviewTable.setForeground(new java.awt.Color(255, 255, 255));
        reviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Puntuación"
            }
        ));
        reviewTable.setToolTipText("");
        reviewTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        reviewTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reviewTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reviewTable.setShowGrid(false);
        jScrollPane1.setViewportView(reviewTable);

        selectedReviewTxt.setEditable(false);
        selectedReviewTxt.setBackground(new java.awt.Color(51, 51, 51));
        selectedReviewTxt.setColumns(20);
        selectedReviewTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectedReviewTxt.setForeground(new java.awt.Color(255, 255, 255));
        selectedReviewTxt.setLineWrap(true);
        selectedReviewTxt.setRows(5);
        selectedReviewTxt.setWrapStyleWord(true);
        jScrollPane2.setViewportView(selectedReviewTxt);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reviews");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar review");

        newReviewTxt.setBackground(new java.awt.Color(51, 51, 51));
        newReviewTxt.setColumns(20);
        newReviewTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newReviewTxt.setForeground(new java.awt.Color(255, 255, 255));
        newReviewTxt.setLineWrap(true);
        newReviewTxt.setRows(5);
        newReviewTxt.setWrapStyleWord(true);
        jScrollPane3.setViewportView(newReviewTxt);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Puntuación");

        newReviewRating.setBackground(new java.awt.Color(51, 51, 51));
        newReviewRating.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newReviewRating.setForeground(new java.awt.Color(255, 255, 255));
        newReviewRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));

        addButton.setBackground(new java.awt.Color(51, 51, 51));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Agregar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(51, 51, 51));
        removeButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Eliminar");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewReviewsProductLayout = new javax.swing.GroupLayout(ViewReviewsProduct);
        ViewReviewsProduct.setLayout(ViewReviewsProductLayout);
        ViewReviewsProductLayout.setHorizontalGroup(
            ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewReviewsProductLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(ViewReviewsProductLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewReviewsProductLayout.createSequentialGroup()
                        .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(newReviewRating, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewReviewsProductLayout.createSequentialGroup()
                        .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeButton)
                            .addComponent(addButton))
                        .addGap(117, 117, 117))))
            .addGroup(ViewReviewsProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movieNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ViewReviewsProductLayout.setVerticalGroup(
            ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewReviewsProductLayout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movieNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewReviewsProductLayout.createSequentialGroup()
                        .addGroup(ViewReviewsProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(ViewReviewsProductLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newReviewRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewReviewsProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewReviewsProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (mainFrame.userAccount == null) {
            mainFrame.showPage("SignInPage", new SignInPage(mainFrame, this));
            return;
        }
        String comment = newReviewTxt.getText();
        System.out.println(newReviewRating.getSelectedItem());
        int rating = Integer.parseInt(newReviewRating.getSelectedItem().toString());
        int idUser = mainFrame.userAccount.getId_user();
        int idProduct = product.getId();
        if (!rated)
            try {
                Insertions.insertReview(comment, rating, idUser, idProduct);
            }
            catch (Exception e) {
                mainFrame.showError("Error al agregar comentario.");
                return;
            }
        else {
            try {
                Deletions.deleteReview(userReviewId);
                Insertions.insertReview(comment, rating, idUser, idProduct);
            }
            catch (Exception e) {
                mainFrame.showError("Error al actualizar la review.");
                return;
            }
        }
        loadData();
        addButton.setText("Actualizar");
        removeButton.setEnabled(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainFrame.showPage("ViewMovie", prev);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
       if (mainFrame.userAccount == null) {
           return;
       }
       try {
           Deletions.deleteReview(userReviewId);
       }
       catch (Exception e) {
           mainFrame.showError("Error al borrar review.");
           return;
       }
       loadData();
       addButton.setText("Agregar");
       removeButton.setEnabled(false);
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainMenuLbl2;
    private javax.swing.JPanel ViewReviewsProduct;
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel movieNameTxt;
    private javax.swing.JComboBox<String> newReviewRating;
    private javax.swing.JTextArea newReviewTxt;
    private javax.swing.JButton removeButton;
    private javax.swing.JTable reviewTable;
    private javax.swing.JTextArea selectedReviewTxt;
    // End of variables declaration//GEN-END:variables
}
